#!/usr/bin/env python3
import argparse
import subprocess
from pathlib import Path

from catalog import (
    WRAPPER_PATH,
    RUN_LOG,
    load_yaml,
    shell_quote,
    load_catalog,
    build_wrapper_command,
)

SCRIPT_DIR = Path(__file__).resolve().parent
BASE_TARGETS = Path("targets.yaml")
CRON_DIR = Path("/etc/cron.d")
MAKEFILE_PATH = Path("Makefile")
WRAPPER_SRC = SCRIPT_DIR / "wrapper.sh"


def install_wrapper():
    wrapper_content = WRAPPER_SRC.read_text()
    existing = WRAPPER_PATH.read_text() if WRAPPER_PATH.exists() else ""
    if existing == wrapper_content:
        return
    WRAPPER_PATH.write_text(wrapper_content)
    WRAPPER_PATH.chmod(0o755)
    print(f"Installed wrapper script to {WRAPPER_PATH}")


def apply_target(target, pull=False, doppler=None):
    if not target.get("enabled", True):
        return False

    name = target["name"]
    repo_path = Path(target["repo_path"])
    schedule_path = repo_path / target["schedule_file"]
    print(f"Applying scheduler for {name}")

    if pull and target.get("branch"):
        subprocess.run(["git", "-C", str(repo_path), "fetch"], check=False)
        subprocess.run(["git", "-C", str(repo_path), "checkout", target["branch"]], check=False)
        subprocess.run(["git", "-C", str(repo_path), "pull", "--rebase"], check=False)

    if not schedule_path.exists():
        print(f"⚠️  Schedule file not found for {name}: {schedule_path}")
        return False

    config = load_yaml(schedule_path)
    defaults = config.get("defaults", {})
    schedules = config.get("schedules", [])

    cron_file = CRON_DIR / f"{name}"
    lines = [f"# Auto-generated cron jobs for {name}\n"]

    log_dir = repo_path / defaults.get("log_dir", "logs")
    log_dir.mkdir(parents=True, exist_ok=True)

    for job in schedules:
        cron = job.get("cron")
        if not cron:
            continue
        command = job["command"]
        log_file = job.get("log_file", f"{defaults.get('log_dir', 'logs')}/{job['name']}.log")
        abs_log_path = repo_path / log_file

        env_vars = defaults.get("env", {})
        env_prefix = " ".join(f'{k}={shell_quote(v)}' for k, v in env_vars.items())

        final_command = f"{env_prefix} {command}" if env_prefix else command

        job_name = f"{name}-{job['name']}"
        doppler_project = doppler.get("project", "") if doppler else ""
        doppler_config = doppler.get("config", "") if doppler else ""

        line = (
            f"{cron} root doppler run --project {shell_quote(doppler_project)} --config {shell_quote(doppler_config)} -- {WRAPPER_PATH} "
            f"{shell_quote(str(abs_log_path))} "
            f"{shell_quote(str(repo_path))} "
            f"{shell_quote(final_command)} "
            f"{shell_quote(job_name)} "
            f"{shell_quote(str(RUN_LOG))} "
            f"{shell_quote(job.get('hc_slug', ''))} "
        )

        lines.append(line)

    new_content = "".join(lines)
    new_content += "\n\n"
    existing_content = cron_file.read_text() if cron_file.exists() else ""

    if new_content == existing_content:
        print(f"⏩ No changes for {name}")
        return False

    cron_file.write_text(new_content)
    print(f"Applied {len(schedules)} schedules for {name}")
    return True


def generate_makefile(config):
    jobs, _ = load_catalog(BASE_TARGETS)
    doppler = config.get("doppler", {})
    targets = []
    rules = []

    for job in jobs:
        targets.append(job["job_id"])
        wrapper_call = build_wrapper_command(job, doppler, log_file_override="/dev/stdout")
        rules.append(f"{job['job_id']}:\n\t{wrapper_call}")

    content = f"# Auto-generated by monorepo-scheduler\n"
    content += f".PHONY: {' '.join(targets)}\n\n"
    content += "\n\n".join(rules) + "\n"

    existing = MAKEFILE_PATH.read_text() if MAKEFILE_PATH.exists() else ""
    if content != existing:
        MAKEFILE_PATH.write_text(content)
        print(f"Generated Makefile with {len(targets)} targets")


def main():
    parser = argparse.ArgumentParser(description="Apply cron schedules from monorepo targets")
    parser.add_argument("--pull", action="store_true", help="Git pull target repos before applying")
    args = parser.parse_args()

    install_wrapper()
    config = load_yaml(BASE_TARGETS)
    doppler = config.get("doppler")

    generate_makefile(config)
    results = [apply_target(t, pull=args.pull, doppler=doppler) for t in config.get("targets", [])]
    changed = any(results)

    if changed:
        subprocess.run(["systemctl", "reload-or-restart", "cron"], check=False)
    else:
        print("⏩ No changes detected, skipping cron restart")

if __name__ == "__main__":
    main()
