
import createClient, { type Middleware } from "openapi-fetch";
import type { paths } from "../../types/schema"; // generated by openapi-typescript
import { useAuthStore } from "@/stores/auth";
import { useRouter } from "vue-router";


const useApi = () => {

    const auth = useAuthStore();
    
    // Use environment variable for API base URL, fallback to current origin in production
    const baseUrl = import.meta.env.VITE_API_BASE_URL || '';

    const authMiddleware: Middleware = {
        async onRequest({ request }) {

            if (!auth.isAuthenticated) {
                useRouter().push('/login');
                throw new Error("Unauthorized");
            }

            request.headers.set("Authorization", auth.getAuthHeader());
            return request;
        },

        async onResponse({ response }) {
            if (response.status === 401) {
                auth.logout();
                useRouter().push('/login');
            }
            return response;
        }
    };

    const client = createClient<paths>({ baseUrl });
    client.use(authMiddleware);


    return { client }
}

export default useApi;